name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.21.0'

    - name: Lint
      uses: Jerome1337/golint-action@v1.0.2

    - name: Build
      run: go build

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out
